Repository epicmaxco/vuestic-admin, pull requests merged in 2018-04, with the labels that each got.

#148 Tree view
  .eslintrc.js
  .gitignore
  build/webpack.prod.conf.js
  package.json
  src/components/ui/icons/Set.vue
  src/components/ui/notifications/Notifications.vue
  src/components/ui/tree-view/TreeView.vue
  src/components/ui/tree-view/TreeViewAdvancedPreview.vue
  src/components/ui/tree-view/TreeViewBasicPreview.vue
  src/components/ui/tree-view/TreeViewEditablePreview.vue
  src/components/ui/tree-view/TreeViewIconsPreview.vue
  src/components/ui/tree-view/TreeViewSelectablePreview.vue
  src/i18n/en.json
  src/router/index.js
  src/sass/_variables.scss
  src/store/modules/menu/ui.js
  src/vuestic-theme/vuestic-components/vuestic-checkbox/VuesticCheckbox.vue
  src/vuestic-theme/vuestic-components/vuestic-radio-button/VuesticRadioButton.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeCategory.demo.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeCategory.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeNode.demo.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeNode.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeRoot.demo.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeRoot.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/vuestic-div-checkbox/SquareWithIcon.demo.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/vuestic-div-checkbox/SquareWithIcon.vue
  src/vuestic-theme/vuestic-components/vuestic-tree-view/vuestic-tree-view-readme.md
  src/vuestic-theme/vuestic-plugin.js
  yarn.lock
Labels: feature, reviewed

#159 Datatables - data and api mode improvements
  package.json
  src/components/dashboard/data-visualisation-tab/DataVisualisation.vue
  src/components/dashboard/data-visualisation-tab/TableData.js
  src/components/tables/Table.vue
  src/vuestic-theme/vuestic-components/vuestic-datatable/VuesticDataTable.vue
  src/vuestic-theme/vuestic-components/vuestic-datatable/datatable-components/FilterBar.vue
  src/vuestic-theme/vuestic-components/vuestic-datatable/datatable-components/ItemsPerPage.vue
Labels: awaiting review

#155 IE11 fixes
  package.json
  src/components/forms/form-wizard/FormWizard.vue
  src/components/layout/navbar/Navbar.vue
  src/components/ui/tree-view/TreeViewEditablePreview.vue
  src/main.js
  src/sass/_override-custom-libs.scss
  src/vuestic-theme/vuestic-components/vuestic-wizard/VuesticWizard.vue
  yarn.lock
Labels: awaiting review

#139 Remove unexistent css classes
  src/vuestic-theme/vuestic-components/vuestic-tabs/VuesticTabs.vue
Labels: awaiting review, improvement

#112 Fix ionicon icons
  src/components/dashboard/DashboardInfoWidgets.vue
  src/vuestic-theme/vuestic-components/vuestic-multi-select/VuesticMultiSelect.vue
  src/vuestic-theme/vuestic-components/vuestic-simple-select/VuesticSimpleSelect.vue
Labels: awaiting review, bug
