Repository epicmaxco/vuestic-admin, pull requests merged in 2019-07, with the labels that each got.

#596 feat(inner-loading): add inner loading component
  src/vuestic-theme/vuestic-components/va-inner-loading/VaInnerLoading.demo.vue
  src/vuestic-theme/vuestic-components/va-inner-loading/VaInnerLoading.vue
  src/vuestic-theme/vuestic-plugin.js
Labels: feature

#598 Fix/pagination - limit visible pages
  src/vuestic-theme/vuestic-components/va-pagination/VaPagination.demo.vue
  src/vuestic-theme/vuestic-components/va-pagination/setPaginationRange.js
  src/vuestic-theme/vuestic-components/va-pagination/setPaginationRange.spec.js
Labels: bug

#603 Refactor/breadcrumbs (#531)
  src/components/admin/app-breadcrumbs/AppBreadcrumbs.vue
  src/components/admin/app-sidebar/AppSidebar.vue
  src/components/admin/app-sidebar/NavigationRoutes.js
  src/components/admin/app-topbar/AppTopbar.vue
  src/i18n/cn.json
  src/i18n/en.json
  src/i18n/pt_br.json
  src/vuestic-theme/vuestic-components/va-breadcrumbs/VaBreadcrumbs.vue
  src/vuestic-theme/vuestic-components/va-sidebar/VaSidebar.demo.vue
  src/vuestic-theme/vuestic-plugin.js
  src/vuestic-theme/vuestic-sass/global/color-themes.demo.vue
Labels: ready to merge, reviewed

#595 Refactor/data-tables
  package-lock.json
  package.json
  src/components/admin/app-sidebar/NavigationRoutes.js
  src/components/dashboard/DashboardTable.vue
  src/components/data-tables/DataTables.vue
  src/components/data-tables/scenarios/VaTableActions.vue
  src/components/data-tables/scenarios/VaTableEmpty.vue
  src/components/data-tables/scenarios/VaTableFilter.vue
  src/components/data-tables/scenarios/VaTableInfiniteScroll.vue
  src/components/data-tables/scenarios/VaTableLoading.vue
  src/components/data-tables/scenarios/VaTableSelect.vue
  src/components/data-tables/scenarios/VaTableServerPagination.vue
  src/components/data-tables/scenarios/VaTableSortingPagination.vue
  src/components/markup-tables/MarkupTables.vue
  src/components/markup-tables/data.json
  src/components/tables/BadgeColumn.vue
  src/components/tables/Tables.vue
  src/components/ui/filters/Filters.vue
  src/components/ui/filters/filtersData.js
  src/components/ui/typography/Typography.vue
  src/fixtures/users.json
  src/i18n/cn.json
  src/i18n/en.json
  src/i18n/es.json
  src/i18n/pt_br.json
  src/router/index.js
  src/vuestic-theme/vuestic-components/va-button-toggle/VaButtonToggle.vue
  src/vuestic-theme/vuestic-components/va-datatable/VaDataTable.vue
  src/vuestic-theme/vuestic-components/va-datatable/data/data-table-styles.js
  src/vuestic-theme/vuestic-components/va-datatable/data/fields-definition.js
  src/vuestic-theme/vuestic-components/va-datatable/data/items-per-page-definition.js
  src/vuestic-theme/vuestic-components/va-datatable/data/query-params.js
  src/vuestic-theme/vuestic-components/va-datatable/datatable-components/FilterBar.vue
  src/vuestic-theme/vuestic-components/va-datatable/datatable-components/ItemsPerPage.demo.vue
  src/vuestic-theme/vuestic-components/va-datatable/datatable-components/ItemsPerPage.vue
  src/vuestic-theme/vuestic-components/va-inner-loading/VaInnerLoading.vue
  src/vuestic-theme/vuestic-components/va-pagination/VaPagination.vue
  src/vuestic-theme/vuestic-components/va-pagination/setPaginationRange.js
  src/vuestic-theme/vuestic-components/va-table/VaTable.demo.vue
  src/vuestic-theme/vuestic-components/va-table/VaTable.vue
  src/vuestic-theme/vuestic-components/va-table/VaTableApiModeExample.vue
  src/vuestic-theme/vuestic-components/va-table/VaTableStaticDataExample.vue
  src/vuestic-theme/vuestic-components/va-table/va-table-docs.md
  src/vuestic-theme/vuestic-plugin.js
  src/vuestic-theme/vuestic-sass/global/ContentClass.demo.vue
  src/vuestic-theme/vuestic-sass/global/_typography.scss
  src/vuestic-theme/vuestic-sass/global/_utility-global.scss
  src/vuestic-theme/vuestic-sass/resources/_mixins.scss
  yarn.lock
Labels: refactoring

#617 Rename data tables
  src/components/dashboard/DashboardTable.vue
  src/components/data-tables/DataTables.vue
  src/components/data-tables/scenarios/DataTableActions.vue
  src/components/data-tables/scenarios/DataTableEmpty.vue
  src/components/data-tables/scenarios/DataTableFilter.vue
  src/components/data-tables/scenarios/DataTableInfiniteScroll.vue
  src/components/data-tables/scenarios/DataTableLoading.vue
  src/components/data-tables/scenarios/DataTableSelect.vue
  src/components/data-tables/scenarios/DataTableServerPagination.vue
  src/components/data-tables/scenarios/DataTableSortingPagination.vue
  src/fixtures/users.json
  src/vuestic-theme/vuestic-components/va-data-table/VaDataTable.demo.vue
  src/vuestic-theme/vuestic-components/va-data-table/VaDataTable.vue
  src/vuestic-theme/vuestic-components/va-data-table/VaDataTableApiModeExample.vue
  src/vuestic-theme/vuestic-components/va-data-table/VaDataTableStaticDataExample.vue
  src/vuestic-theme/vuestic-components/va-data-table/va-data-table-docs.md
  src/vuestic-theme/vuestic-components/va-table/VaTable.demo.vue
  src/vuestic-theme/vuestic-plugin.js
Labels: refactoring

#607 Feat/Va list
  src/components/admin/app-sidebar/NavigationRoutes.js
  src/components/lists/Lists.vue
  src/components/lists/data.json
  src/i18n/en.json
  src/i18n/es.json
  src/i18n/pt_br.json
  src/router/index.js
  src/vuestic-theme/vuestic-components/va-avatar/VaAvatar.vue
  src/vuestic-theme/vuestic-components/va-list/VaItem.vue
  src/vuestic-theme/vuestic-components/va-list/VaItemLabel.vue
  src/vuestic-theme/vuestic-components/va-list/VaItemSection.vue
  src/vuestic-theme/vuestic-components/va-list/VaList.demo.vue
  src/vuestic-theme/vuestic-components/va-list/VaList.vue
  src/vuestic-theme/vuestic-components/va-list/VaListLabel.vue
  src/vuestic-theme/vuestic-components/va-list/VaListSeparator.vue
  src/vuestic-theme/vuestic-components/va-list/va-list-docs.md
  src/vuestic-theme/vuestic-plugin.js
  src/vuestic-theme/vuestic-sass/grid/_grid-global-styles.scss
  src/vuestic-theme/vuestic-sass/resources/_variables.scss
Labels: feature

#621 fix: open menu item in a new tab
  src/components/admin/app-sidebar/components/SidebarLink.vue
  src/components/admin/app-sidebar/components/SidebarLinkGroup.vue
  src/vuestic-theme/vuestic-components/va-sidebar/VaSidebar.vue
Labels: bug, ready to merge, reviewed
